### ISSUE TITLE
Параллельный запуск

### ISSUE THREAD

**Issue by Sergey111991KV** [pf03/newBot#10]
Добавь еще возможность одновременной работы обоих ботов, а не только одного из)

**Comment by pf03** [comment]
Я бы с радостью, но хотелось бы завершить ревью хотя бы к концу года)) На риззоме нет такого требования. 
![run_parallel](https://user-images.githubusercontent.com/15140589/119129027-113f5000-ba3f-11eb-9466-bf3b31db143a.png)

**Comment by pf03** [comment]
Хотя технически это не сложно. Сделать два forkIO с разными конфигами

**Comment by Sergey111991KV** [comment]
Ну да) не обязательно запускать параллельно, но эта возможность должна быть, тут типа другими словами - помимо параллельного запуска должна быть возможность запускать боты по одному.

**Comment by Sergey111991KV** [comment]
Это не сложно, библиотек достаточно, главное чтобы работало корректно)

**Comment by KateBushueva** [comment]
> Добавь еще возможность одновременной работы обоих ботов, а не только одного из)

не совсем поняла, что ты хочешь.. У меня запускается или один бот, или второй, зачем делать параллельный запуск?

**Comment by pf03** [comment]
> > Добавь еще возможность одновременной работы обоих ботов, а не только одного из)
> 
> не совсем поняла, что ты хочешь.. У меня запускается или один бот, или второй, зачем делать параллельный запуск?

Ну вот, а я уже вчера это почти доделал. Правда, не уверен что эти forkIO будут корректно работать

**Comment by Sergey111991KV** [comment]
```
не совсем поняла, что ты хочешь.. У меня запускается или один бот, или второй, зачем делать параллельный запуск?

```


Ну смотри, если тебе нужно запустить бота, который будет отвечать и на сообщения в телеграмме и на сообщения в vk, тебе нужно один и тот же проект два раза запускать? я считаю, это плохо масштабируется, что не говори) суть на этих двух сервисах посмотреть простейшую параллельную работу - глубокие знания не обязательны, главное понимание)

**Comment by pf03** [comment]
В новой версии я сделал параллельного бота. В конфиг добавил флаг forks для переключения режимов - параллельные боты или единственный бот. Сразу вскрылось два косяка, как я и думал. 1) переплетение эффектов при записи в лог/терминал. 2) параллельный бот не закрывается по Ctrl+C
Пока не исправил

**Comment by pf03** [comment]
Переписал запуск трансформеров через forConcurrently_ из пакета async вместо простых forkIO
Исправил остановку через Ctrl+C
Переплетение эффектов технически может быть, но оно не заметно в этой реализации, так как вычисления в STM имеют меньшую степень справедливости, чем обычные forkIO
