### ISSUE TITLE
Опять названия

### ISSUE THREAD

**Issue by Sergey111991KV** [pf03/newBot#12]
Пойми что мы не хотим придираться, но вот когда я увидел LBS - я понял, что это значит, но мне кажется делать свой синоним к этому лишне, обычно в файле пишут это в квалифицированных импортах, тем более для обычного у тебя type BS = BC.ByteString, что не симметрично) а еще у тебя много синонимов, которые лучше тогда уже обернуть в newtype, ты же знаешь их полезное свойство? код будет более безопаснее от этого.

**Comment by pf03** [comment]
Убрал LBS, BS и заменил синонимы type на newtype
LBS, BS у меня больше используется в сервере, здесь оно не сильно нужно.  Там можно будет обернуть в newtype
