### ISSUE TITLE
Варнинги компилятора

### ISSUE THREAD

**Issue by antonkalinin-ml** [pf03/newBot#13]
В задании 5 имеется требование: 

> Весь проект скомпилирован с флагами -Wall и -Werror и нет ни одной ошибки и ни одного варнинга от компилятора. 

Эти флаги нужно добавить в package.yaml или компилировать проект командой `stack build --pedantic`. В таком случае выдается ошибка, которую нужно исправить:

```
/home/kav/s/test/newBot/src/Interface/Log/Functions.hs:143:5: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘writeFile’ shadows the existing binding
      imported from ‘Prelude’ at src/Interface/Log/Functions.hs:20:1-29
      (and originally defined in ‘System.IO’)
    |
143 |     writeFile str = do
    |     ^^^^^^^^^

```

**Comment by pf03** [comment]
Привет. Я обычно делаю так 
`stack build --ghc-options="-Wall -Werror"`, 
в этот раз просто забыл. Исправлено
