### ISSUE TITLE
прописать возможности бота в ридми

### ISSUE THREAD

**Issue by KateBushueva** [pf03/newBot#18]
Прописать, что конктретно умеет бот. Если вк-бот не может работать с фото, картами и т.п. это должно быть прописано в ридми. Кроме того, отправка, допустим, фото не должна приводить к ошибке и аварийному завершению работы - можно просто игнорировать такие сообщения или информировать пользователя, что бот не работает с фотографиями.

**Comment by KateBushueva** [comment]
вот это еще надо исправить

**Comment by pf03** [comment]
исправил
