### ISSUE TITLE
Запуск бота

### ISSUE THREAD

**Issue by KateBushueva** [pf03/newBot#2]
Проверь поля в конфиг-файле. У тебя у структуры ConfigApp, которая парсится из джейсона по умолчанию, есть поле updateIdFromFile , а в шаблоне конфиг-файла такого поля нет

**Comment by pf03** [comment]
Файл config-example.json слегка устарел, заменил на новый

**Comment by KateBushueva** [comment]
да, Telegram запускается, 
VK при парсинге апдейтов выдает ошибку следующего содержания
![err1](https://user-images.githubusercontent.com/80405655/118389795-4b21e800-b634-11eb-9c98-09ebcec54652.png)

**Comment by pf03** [comment]
Возможно проблема в настройках бота (см картинку ниже). Добавил информацию об этом в Readme, а также побольше отладочных логов
![vk_bot_settings](https://raw.githubusercontent.com/pf03/newBot/main/vk_bot_settings.png)

**Comment by KateBushueva** [comment]
Я запустила ВК бота, однако мне пришлось поменять парсинг сообщений в модуле `VK.Parse`. Посмори внимательно:
- вк сообщения не содержат user_id, а содержат from_id
- from_id лежит не в основном объекте "object", а во вложенном объекте "message"
- текст сообщения лежит не в "body", а в "text" и тоже внутри "message"
Это надо исправить, потестировать у себя и запушить в репозиторий

**Comment by pf03** [comment]
Странно, а как же у меня работает? Проверю это

**Comment by KateBushueva** [comment]
по поводу вк бота - проблема была у меня - у меня версия апи стояла 5.124, на версии 5.5 все запускается корректно. По этому ишью больше вопросов нет, закрываем.
