### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by KateBushueva** [pf03/newBot#3]
Используй ormolu для форматирования проекта

**Comment by pf03** [comment]
использовал

**Comment by KateBushueva** [comment]
используй 
cd src && ormolu --mode inplace $$(find . -name '*.hs') 
чтобы отформатить все файлы из src сразу, а то у тебя не везде форматирование прошло

**Comment by Sergey111991KV** [comment]
да во всех основных файлах ты прошел им молодец, просто в некоторых не до конца) Если бы мне не делали миллион замечаний по этому по воду, то я бы наверное на это не обращал внимания, а сейчас мне это тоже в глаза бросается, так что будь внимательнее)

**Comment by Sergey111991KV** [comment]
я не знаю можно ли весь проект пройти ормулой, но прохожу по одному файлу

**Comment by pf03** [comment]
> я не знаю можно ли весь проект пройти ормулой, но прохожу по одному файлу

прошел ормулой по всем файлам
