### ISSUE TITLE
Управление ботом

### ISSUE THREAD

**Issue by KateBushueva** [pf03/newBot#4]
Пропиши, пожалуйста, в ридми, управление ботом: 
- где и как выставляется приоритет логгирования (это можно найти в коде, но для ревьюера удобно видеть это в ридми)
- если у тебя предусмотрен выход из бота через введение команды в консоль, это тоже в ридми должно быть прописано

**Comment by KateBushueva** [comment]
про приоритет логгирования теперь увидела в конфиге, но все равно лучше в ридми добавить. И допустимые значение тоже надо прописать (это, кстати, намек, что должна быть проверка данных из файла на корректность)

**Comment by KateBushueva** [comment]
согласно заданию, должна быть возможность установить начальное количество повторов для пользователей. Не нашла этого в конфиг-файле

**Comment by pf03** [comment]
> согласно заданию, должна быть возможность установить начальное количество повторов для пользователей. Не нашла этого в конфиг-файле

Да, действительно у меня предусмотрено только количество повторов для конкретного пользователя (repeatNumber) Для всех пользователей сразу я не прописывал, значит неправильно понял задание

**Comment by pf03** [comment]
> согласно заданию, должна быть возможность установить начальное количество повторов для пользователей. Не нашла этого в конфиг-файле

добавил поле defaultRepeatNumber в config.json

**Comment by pf03** [comment]
> про приоритет логгирования теперь увидела в конфиге, но все равно лучше в ридми добавить. 

добавил
> И допустимые значение тоже надо прописать (это, кстати, намек, что должна быть проверка данных из файла на корректность)

добавил проверку на корректность для repeatNumber, log.minLevel. Остальные поля проверяет сам aeson при парсинге, по крайней мере по типам

**Comment by KateBushueva** [comment]
По поводу ридми осталось поправить:
- пункт 2: файл уже присутствует, не нужно вводить в заблуждение;
- нумерация в первом разделе: 1,2,3,5 - потерял 4
больше по этому ишью у меня вопросов нет

**Comment by pf03** [comment]
> По поводу ридми осталось поправить:
> 
> * пункт 2: файл уже присутствует, не нужно вводить в заблуждение;

Это я имел в виду,  что если exe-шник запускать отдельно (a не stack ghci как обычно) , то к нему в папку нужно скопировать файл конфига. 
Ну не проблема удалить

**Comment by Sergey111991KV** [comment]
отлично)
