### ISSUE TITLE
Использование потоков

### ISSUE THREAD

**Issue by KateBushueva** [pf03/newBot#5]
Объясни, пожалуйста, за что у тебя отвечает каждый поток.

**Comment by pf03** [comment]
Собственно по потокам никаких требований не было. Я их использую только для выхода из приложения. Первый поток считывает команду пользователя и асинхронно закрывает второй поток (цикл работы бота), если команда равна q. Второй поток по завршении своей работы по ошибке или по команде пользователя, асинхронно закрывает первый поток. После чего закрывается главный поток.

**Comment by KateBushueva** [comment]
По поводу потоков смотри, что у тебя получается: 
- ты форкаешь основной поток и в отдельном потоке работаешь с консолью для выхода из приложения - в принципе норм;
- далее ты форкаешь основной поток и в отдельном потоке работаешь с ботом - тут у меня вопрос: почему не в основном? на мой взгляд, этот поток лишний.
- такой момент: при получении в консоли команды q ты закрываешь поток, в котором работает бот, через бросание исключения - вот так делать плохо. Корректный выход из программы не должен осуществляться через бросание исключения.

**Comment by KateBushueva** [comment]
В принципе, можно было обойтись одним потоком - проще сделать безопасный вариант бота - но тут твое дело

**Comment by pf03** [comment]
Убрал потоки, остановка через ctrl+c
