### ISSUE TITLE
вопрос по логике

### ISSUE THREAD

**Issue by KateBushueva** [pf03/newBot#6]
В твоей имплементации количество повторов влияет только на текст (смотрела пока только телеграм) - ты просто копируешь текст заданное количество раз в одном ответном сообщении. При этом вложения отправляются только один раз. Если сообщение состоит только из картинки, то в ответ мы получаем одну картинку, повтора не будет.
Корректная имплементация подразумевает, что отправляться заданное количество раз должно все сообщение (а не только текст в нем).

**Comment by pf03** [comment]
Переделал логику следующим образом:
1) сообщение без вложений "foo" отправляется обратно как "foo foo foo"
2) сообщение с вложениями отправляется обратно n раз в том же виде, как и пришло

**Comment by pf03** [comment]
> Переделал логику следующим образом:
> 
> 1. сообщение без вложений "foo" отправляется обратно как "foo foo foo"
> 2. сообщение с вложениями отправляется обратно n раз в том же виде, как и пришло

Или первый способ вообще убрать и все сообщения обрабатывать вторым способом? Тогда часть моей логики излишняя. Да и бот не будет иметь смысла. Первый способ дает возможность легко сделать бота более "осознанным", достаточно заменить функцию Logic.answerMessageCommand

**Comment by KateBushueva** [comment]
задачи сделать бота "осознанным" не стояла )) 
я не против оставить как есть, если условия задания соблюдаются
